In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 2. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**2.1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [5]:
numerator = 2 ** np.arange(1, 21)
denominator = np.arange(1, 21)
numerator / denominator

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [10]:
sigma = np.arange(6) # i от нуля до 5
np.sum(0.1 ** (sigma * 3)  *  0.2 ** (sigma * 4))

1.00000160000256

**2.3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [15]:
## your code
zero = np.zeros([8,8])
zero[0::2, 1::2] = 1 # заполнение первой строки и далее через одну
zero[1::2, 0::2] = 1 # заполнение второй строки и далее
zero

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

**2.4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [70]:
np.random.seed(777)
X = np.random.random((5, 2))

## your code
## http://xlench.bget.ru/doku.php/mat/elem/decart

x = X[:, 0]
y = X[:, 1]

teta = np.arctan(y / x)
ro = x / np.cos(teta)

print(str(ro) + ' -- Полярный радиус')
print(str(teta) + ' -- Полярный угол')

[0.33871188 0.46402592 1.24778674 1.05787496 0.69802944] -- Полярный радиус
[1.10322617 1.43670313 0.83741172 0.81314607 1.17486856] -- Полярный угол


**2.5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [115]:
# https://www.geeksforgeeks.org/numpy-argmax-python/
# https://stackoverflow.com/questions/9482550/argmax-of-numpy-array-returning-non-flat-indices
np.random.seed(777)
X = np.random.random((10, 10))

## your code
print(np.unravel_index(np.argmax(X), X.shape))

# Или
print(np.argmax(X) // X.shape[1]) # по x
print(np.argmax(X) % X.shape[1]) # по y

(9, 2)
9
2


**2.6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [48]:
np.random.seed(7772)
X = np.random.random((10, 2))
y = np.random.random((1, 2))

# dist = sqrt((x_a - x_b)ˆ2 + (y_a - y_b)ˆ2)
#                  ^               ^
#                x_diff          y_diff

x_diff = X[:, 0] - y[:, 0]
y_diff = X[:, 1] - y[:, 1]
dist = np.sqrt(x_diff ** 2 + y_diff ** 2)

np.argmin(dist)

4

**2.7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [50]:
# https://numpy.org/doc/stable/reference/generated/numpy.vectorize.html

def myfunc(x):
    if x < 0:
        return x ** 2 + 2 * x + 6
    elif x >= 2:
        return x ** 2 + 4 * x - 4
    else:
        return x + 6

vfunc = np.vectorize(myfunc)
vfunc(np.arange(-3, 3.01, 0.01))

array([ 9.    ,  8.9601,  8.9204,  8.8809,  8.8416,  8.8025,  8.7636,
        8.7249,  8.6864,  8.6481,  8.61  ,  8.5721,  8.5344,  8.4969,
        8.4596,  8.4225,  8.3856,  8.3489,  8.3124,  8.2761,  8.24  ,
        8.2041,  8.1684,  8.1329,  8.0976,  8.0625,  8.0276,  7.9929,
        7.9584,  7.9241,  7.89  ,  7.8561,  7.8224,  7.7889,  7.7556,
        7.7225,  7.6896,  7.6569,  7.6244,  7.5921,  7.56  ,  7.5281,
        7.4964,  7.4649,  7.4336,  7.4025,  7.3716,  7.3409,  7.3104,
        7.2801,  7.25  ,  7.2201,  7.1904,  7.1609,  7.1316,  7.1025,
        7.0736,  7.0449,  7.0164,  6.9881,  6.96  ,  6.9321,  6.9044,
        6.8769,  6.8496,  6.8225,  6.7956,  6.7689,  6.7424,  6.7161,
        6.69  ,  6.6641,  6.6384,  6.6129,  6.5876,  6.5625,  6.5376,
        6.5129,  6.4884,  6.4641,  6.44  ,  6.4161,  6.3924,  6.3689,
        6.3456,  6.3225,  6.2996,  6.2769,  6.2544,  6.2321,  6.21  ,
        6.1881,  6.1664,  6.1449,  6.1236,  6.1025,  6.0816,  6.0609,
        6.0404,  6.0

**2.8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [62]:
np.random.seed(7772)
X = np.random.random((10, 10))

# https://stackoverflow.com/questions/39441517/in-numpy-sum-there-is-parameter-called-keepdims-what-does-it-do
np.mean(X - np.mean(X, axis=1, keepdims=True), axis = 1)

array([-3.33066907e-17,  1.11022302e-17, -5.55111512e-17, -2.22044605e-17,
        1.11022302e-17,  6.66133815e-17,  3.33066907e-17,  4.44089210e-17,
        3.33066907e-17, -2.22044605e-17])

**2.9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [72]:
np.random.seed(7772)
X = np.random.normal(loc=5, scale=2., size=1000)

# https://ru.wikipedia.org/wiki/%D0%92%D1%8B%D0%B1%D0%BE%D1%80%D0%BE%D1%87%D0%BD%D0%BE%D0%B5_%D1%81%D1%80%D0%B5%D0%B4%D0%BD%D0%B5%D0%B5
# https://ru.wikipedia.org/wiki/%D0%92%D1%8B%D0%B1%D0%BE%D1%80%D0%BE%D1%87%D0%BD%D0%B0%D1%8F_%D0%B4%D0%B8%D1%81%D0%BF%D0%B5%D1%80%D1%81%D0%B8%D1%8F

samp_mean = np.sum(X) / len(X) # или просто np.mean(X)
samp_var = np.sum((X - samp_mean) ** 2) / len(X) # или просто np.var(X)
print(samp_mean)
print(samp_var)

5.033608062695477
4.143962446244119


**2.10.** Создать матрицу (NB. БЕЗ ЦИКЛОВ И ИЗМЕНЕНИЯ ОТДЕЛЬНЫХ ЭЛЕМЕНТОВ):

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [11]:
## your code

**2.11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [12]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 0, 4, 0, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [13]:
## your code
# https://www.w3resource.com/python-exercises/basic/python-basic-1-exercise-92.php